Update sierra_leone_address_hierarchy_entries.csv
PIH/openmrs-config-pihsl pull request #129
Opened 2024-02-15 23:29 UTC by bhsesay

I just added the Districts and Chiefdoms with few changes to Port Loko and Bombali Districts

2024-02-15 23:37 UTC, lnball commented on configuration/addresshierarchy/sierra_leone_address_hierarchy_entries.csv
> +Sierra Leone|Karena|Buya
Move these to where Karena belongs alphabetically (instead of at the end of the file)

2024-02-15 23:37 UTC, lnball commented on configuration/addresshierarchy/sierra_leone_address_hierarchy_entries.csv
> +Sierra Leone|Falaba|Delemandugu
Move these to where Falaba belongs alphabetically (instead of at the end of the file)

2024-02-15 23:38 UTC, lnball requested changes
Looks good to me @bhsesay .  Just move the 2 sections and I'll approve the github pull request (PR).

2024-02-16 00:01 UTC, bhsesay reviewed
Putting the districts in alphabetical order.

2024-02-16 00:06 UTC, bhsesay commented
This has been updated. Thank you Ellen!

2024-02-16 18:24 UTC, merged