UHM-7443 and UHM-7992 - pregnancy program dashboard
PIH/openmrs-config-pihsl pull request #178
Opened 2024-08-14 22:14 UTC by mseaton

2024-08-14 22:25 UTC, mseaton reviewed
There are certainly improvements / optimizations we can make here via AppTemplates or related new features to support removing boilerplate code.  Something to iterate on, but this should work for now.

2024-08-14 22:26 UTC, mseaton reviewed
We also have the option, if we choose, to make each of the apps in here into a separate file, if we find that easier to follow.

2024-08-15 13:57 UTC, mogoodrich approved these changes
I like having a file-per-program, as you have, not per widget.

Even though this is likely a better approach, I'm still a little hesitant about doing this dashboard configuration different than the rest, but I guess if this new way doesn't become the pattern we follow going forward, it should be straightforward to incorporate this into the CALF
 
I added @lnball  and @andycottonpih  as reviewers as an FYI.  @andycottonpih  no action required from you, just wanting to copy you in in case you start to work on this stuff in the future.

2024-08-15 14:21 UTC, lnball requested changes
Hard to review without testing the code but looks good.

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +      "label": "RECENT VISITS"
This should be a message code.

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "ANC INITIAL FORM",
Another code here.  I don't think FORM should be in the name.

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "ANC FOLLOWUP FORM",
Same.  Another code here.  I don't think FORM should be in the name.

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "POSTPARTUM DAILY PROGRESS",
And here

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "LABOR AND DELIVERY SUMMARY",
And here

2024-08-15 14:21 UTC, lnball commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "MATERNAL ADMISSION",
And here

2024-08-15 14:24 UTC, merged

2024-08-15 14:28 UTC, mseaton commented on configuration/appframework/pregnancy_dashboard_app.json
> +      "label": "RECENT VISITS"
I didn't bother with message codes here for now, since I didn't think we supported any languages other than english in Sierra Leone, and this is in the SL config.  But I can change if we feel otherwise.

2024-08-15 14:29 UTC, mseaton commented on configuration/appframework/pregnancy_dashboard_app.json
> +    "label": "ANC INITIAL FORM",
Generally have the same feeling about the "FORM" in the name, but that's what the requirements stated, so it's what I went with.  Easy enough to change it here as needed.

2024-08-15 14:33 UTC, andycottonpih commented
No comments on the content, but on structure I agree with Mark that I like the file-per-program approach you used.  JSON is structured enough that I don't think separate files would make things any easier to follow.